### ISSUE TITLE
language tagged literals may be invalid

### ISSUE THREAD

**Issue by pchampin** [Tpt/oxigraph#24]
No check is performed on the language tag passed to `Literal::new_language_tagged_literal`. It may be non compliant with BCP47, making the literal invalid per the [RDF spec](https://www.w3.org/TR/rdf11-concepts/#h3_section-Graph-Literal).

You might want to use https://crates.io/crates/language-tag.

Note that this would change the API, as `Literal::new_language_tagged_literal` should now return a `Result`. In that case, an *unchecked* version of this function would also be nice.

**Comment by Tpt** [comment]
Indeed, I should add a check.

I would prefer not use `language-tag` because its data structures are quite heavy. I contributed a rewrite of `language-tags` with a design similar to `Url` but a new version never got released.

Maybe this checking code should be in Rio if we want to fully validate language tags in Turtle (currently we only check if the language tags matches `[a-z]+(-[a-zA-Z0-9]+)*` like specified by Turtle. What do you think about it?

**Comment by pchampin** [comment]
Rio sounds like a good place for this.

**Comment by Tpt** [comment]
ok, let's go for it.
