### ISSUE TITLE
`oxigraph::Error` does not implement `std::error::Error`

### ISSUE THREAD

**Issue by pchampin** [Tpt/oxigraph#25]
Everything is in the title...

This hinders interoperability with other libraries.

I was about to propose a PR, but then I realized that `oxigraph::Error` is just a pub use of `failure::Error` so I could not just add an `impl std::error::Error for Error` block... :-/

**Comment by Tpt** [comment]
Yes, indeed. I am thinking about migrating to something else, maybe `anyhow` that implements `Error` except if you have a better idea.

**Comment by pchampin** [comment]
In Sophia, we use `thiserror`, which is simple and efficient.

**Comment by Tpt** [comment]
Thank you! I'll investigate `thiserror`.

**Comment by Tpt** [comment]
I settled on using `anywhow` because `oxigraph` sometimes provides closures that the user could implement. This way any error returned by the closures could be seamlessly converted to `oxigraph::Error`.

In the future, it would be nice to provide special error types that do not require allocation for functions that might fail often in some use cases (like the `NamedNode` constructor).

**Comment by pchampin** [comment]
Now I'm confused... apparently, `anyhow::Error` does not implement `std::error::Error` either... :-/

It "supports"" `std::error::Error` by implementing `From<E: std::error::Error>`, but itself does not implement it... Frustrating...

**Comment by Tpt** [comment]
Indeed. I should have checked again more carefully. My memory is playing me games. I'm trying an other approach right now.

**Comment by Tpt** [comment]
I just pushed a custom `Error` type for oxigraph that could wrap any errors and have simpler variants for common error types. This way, simple common errors like `IriParseError` do not require allocation but any type implementing `std::error::Error` is supported.

This type implements `std::error::Error`.
